--AUCTION TABLE
--ALTER TABLE AUCTION DROP CONSTRAINT AUCTION_PLAYER_ID_FK;
--ALTER TABLE AUCTION DROP CONSTRAINT AUCTION_SOLD_TO_SEASON_ID_FK;
ALTER TABLE AUCTION ADD CONSTRAINT AUCTION_SOLD_TO_SEASON_ID_FK  FOREIGN KEY (SOLD_TO,SEASON_ID) 
REFERENCES TEAMS(TEAM_ID,SEASON_ID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE AUCTION ADD CONSTRAINT AUCTION_PLAYER_ID_FK FOREIGN KEY (PLAYER_ID) 
REFERENCES PLAYERS(PLAYER_ID) ON UPDATE CASCADE ON DELETE CASCADE;

--BATTING_PERFORMANCE ,BOWLING_PERFORMANCE,FIELDING_PERFORMANCE TABLE
 --ALTER TABLE BATTING_PERFORMANCE DROP CONSTRAINT batting_performance_player_id_season_id_fkey;
 --ALTER TABLE BOWLING_PERFORMANCE DROP CONSTRAINT bowling_performance_player_id_season_id_fkey;
 --ALTER TABLE FIELDING_PERFORMANCE DROP CONSTRAINT fielding_performance_player_id_season_id_fkey;
 ALTER TABLE BATTING_PERFORMANCE ADD CONSTRAINT batting_performance_player_id_season_id_fk FOREIGN KEY (player_id, season_id)
 REFERENCES AUCTION(player_id, season_id)  ON UPDATE CASCADE ON DELETE CASCADE;
 ALTER TABLE BOWLING_PERFORMANCE ADD CONSTRAINT bowling_performance_player_id_season_id_fk FOREIGN KEY (player_id, season_id)
 REFERENCES AUCTION(player_id, season_id)  ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE FIELDING_PERFORMANCE ADD CONSTRAINT fielding_performance_player_id_season_id_fk FOREIGN KEY (player_id, season_id)
 REFERENCES AUCTION(player_id, season_id)  ON UPDATE CASCADE ON DELETE CASCADE;
 
 ALTER TABLE PERFORMANCE ADD CONSTRAINT PERFORMANCE_PLAYER_ID_SEASON_ID_FK FOREIGN KEY(PLAYER_ID,SEASON_ID)
 REFERENCES AUCTION(PLAYER_ID,SEASON_ID) ON UPDATE CASCADE ON DELETE CASCADE;
 ALTER TABLE PERFORMANCE ADD CONSTRAINT PERFORMANCE_PLAYER_ID_SEASON_ID_PK PRIMARY KEY(PLAYER_ID,SEASON_ID);

 --POINTSTABLE
 --ALTER TABLE POINTS_TABLE DROP CONSTRAINT points_table_team_id_season_id_fkey;
ALTER TABLE POINTS_TABLE ADD CONSTRAINT POINTS_TABLE_TEAM_ID_SEASON_ID_FK FOREIGN KEY(TEAM_ID,SEASON_ID) 
REFERENCES TEAMS(TEAM_ID,SEASON_ID) ON UPDATE CASCADE ON DELETE CASCADE;

--TEAMS(CAPTAIN)
/*ALTER TABLE TEAMS DROP CONSTRAINT teams_captain_id_fkey;
ALTER TABLE TEAMS ADD CONSTRAINT teams_captain_id_fk FOREIGN KEY (captain_id)
REFERENCES players (player_id) ON UPDATE CASCADE ON DELETE CASCADE;
*/
--SEASON TABLE
--ALTER TABLE SEASON DROP CONSTRAINT season_runner_id_season_id_fkey;
--ALTER TABLE SEASON DROP CONSTRAINT season_winner_id_season_id_fkey;
ALTER TABLE SEASON ADD CONSTRAINT season_runner_id_season_id_fk FOREIGN KEY (runner_id, season_id)
REFERENCES teams (team_id, season_id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE SEASON ADD CONSTRAINT season_winner_id_season_id_fk FOREIGN KEY (winner_id, season_id)
REFERENCES teams (team_id, season_id) ON UPDATE CASCADE ON DELETE CASCADE;